config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks

  validates :name, length: {in: 4..30}
  validates :user, presence: true

  accepts_nested_attributes_for :tasks, allow_destroy: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates_presence_of :name, :description
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, foreign_key: 'user_id'
  has_many :tasks, foreign_key: 'project_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @project = Project.includes(:user)
  end

  def show
  	# @project = Project.find(params[:id])
  end

  def new
  	@project = Project.new
  end

  def create
  	@project = current_user.project.new(project_params)

  	if @project.save
  		redirect_to project_path
  	else
  		render :new
  	end
  end

  def edit
  	# @project = Project.find(params[:id])
  end

  def update
  	# @project = Project.find(params[:id])
  	if @project.update(project_params)
  		redirect_to project_path
  	else
  		render :edit
  	end
  end

  def destroy
  	# @project = Project.find(params[:id])
  	@project.destroy
  	redirect_to project_path
  end

private

	def find_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, tasks_attributes: task_params)
	end

  def task_params
    [:id, :description,:due_date, :_destroy, :user_id, :name]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pm
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/projects/edit.html.haml
= simple_form_for @project do |f|
	= f.input :name
	= f.submit
/ end

app/views/projects/index.html.haml
.fildset
  = nested_form_for @project do |f|
    = f.input :name
    = f.fields_for :tasks do |task_form|
      - if task_form.object.new_record?
        = task_form.association :user, label_method: :email, value_method: :id
        = task_form.input :name
        = task_form.input :description, as: :text
        = task_form.input :due_date
        = task_form.link_to_remove "Remove this task"

        %p
          = f.link_to_add "Add a task", :tasks
          = f.submit

app/views/projects/new.html.haml
= simple_form_for @project do |f|
	= f.input :name
	= f.submit
end

app/views/projects/show.html.haml
%h1 Project
%b= @project.name
%p= @project.owner.email
= link_to "All projects", projects_path

app/views/welcome/index.html.haml
.container
  .col_sm
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et laboriosam ipsa repudiandae porro libero quam magnam adipisci recusandae aut, cupiditate dolor natus, unde veritatis esse saepe vitae consequatur error repellat.
    %p= number_to_currency(123.45)
    = link_to "Sign in", new_user_session_path